export const MY_STATUS = 'my-status'
export const USER_STATUS = 'user-status'
export const USER_STATUS_RESPONSE = 'user-status-response'

export const RECEIVE_MESSAGE = 'receive-message'
export const UPDATE_CHAT = 'update-chat'
export const SEND_MESSAGE = 'send-message'
export const MESSAGE_READ = 'message-read'
export const TYPING = 'typing'
export const TYPING_STOPPER = 'typing-stopped'
